/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups/route'
import { Route as IndexImport } from './routes/index'
import { Route as GroupsAddRouteImport } from './routes/groups/add/route'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId/route'
import { Route as GroupsGroupIdTasksRouteImport } from './routes/groups/$groupId/tasks/route'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const GroupsRouteRoute = GroupsRouteImport.update({
  path: '/groups',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GroupsAddRouteRoute = GroupsAddRouteImport.update({
  path: '/add',
  getParentRoute: () => GroupsRouteRoute,
} as any)

const GroupsGroupIdRouteRoute = GroupsGroupIdRouteImport.update({
  path: '/$groupId',
  getParentRoute: () => GroupsRouteRoute,
} as any)

const GroupsGroupIdTasksRouteRoute = GroupsGroupIdTasksRouteImport.update({
  path: '/tasks',
  getParentRoute: () => GroupsGroupIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/groups': {
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/groups/$groupId': {
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof GroupsRouteImport
    }
    '/groups/add': {
      preLoaderRoute: typeof GroupsAddRouteImport
      parentRoute: typeof GroupsRouteImport
    }
    '/groups/$groupId/tasks': {
      preLoaderRoute: typeof GroupsGroupIdTasksRouteImport
      parentRoute: typeof GroupsGroupIdRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  GroupsRouteRoute.addChildren([
    GroupsGroupIdRouteRoute.addChildren([GroupsGroupIdTasksRouteRoute]),
    GroupsAddRouteRoute,
  ]),
  LoginRoute,
  SignupRoute,
])

/* prettier-ignore-end */
