name: Setup
description: Install everything for the repo

inputs:
  bun-version:
    description: Version of bun to use
    default: latest

runs:
  using: composite
  steps:
    - name: 🏗 Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 📦 Install deps
      run: bun install
      shell: bash
