/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthUsernameRouteImport } from "./routes/_auth/$username";
import { Route as AuthTasksIndexRouteImport } from "./routes/_auth/tasks.index";
import { Route as AuthProjectsIndexRouteImport } from "./routes/_auth/projects.index";
import { Route as AuthTasksTaskIdRouteImport } from "./routes/_auth/tasks.$taskId";
import { Route as AuthProjectsProjectIdRouteImport } from "./routes/_auth/projects.$projectId";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthUsernameRoute = AuthUsernameRouteImport.update({
  id: "/$username",
  path: "/$username",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthTasksIndexRoute = AuthTasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthTasksTaskIdRoute = AuthTasksTaskIdRouteImport.update({
  id: "/tasks/$taskId",
  path: "/tasks/$taskId",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthProjectsProjectIdRoute = AuthProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => AuthRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/$username": typeof AuthUsernameRoute;
  "/projects/$projectId": typeof AuthProjectsProjectIdRoute;
  "/tasks/$taskId": typeof AuthTasksTaskIdRoute;
  "/projects": typeof AuthProjectsIndexRoute;
  "/tasks": typeof AuthTasksIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/$username": typeof AuthUsernameRoute;
  "/projects/$projectId": typeof AuthProjectsProjectIdRoute;
  "/tasks/$taskId": typeof AuthTasksTaskIdRoute;
  "/projects": typeof AuthProjectsIndexRoute;
  "/tasks": typeof AuthTasksIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/signup": typeof SignupRoute;
  "/_auth/$username": typeof AuthUsernameRoute;
  "/_auth/projects/$projectId": typeof AuthProjectsProjectIdRoute;
  "/_auth/tasks/$taskId": typeof AuthTasksTaskIdRoute;
  "/_auth/projects/": typeof AuthProjectsIndexRoute;
  "/_auth/tasks/": typeof AuthTasksIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/signup"
    | "/$username"
    | "/projects/$projectId"
    | "/tasks/$taskId"
    | "/projects"
    | "/tasks";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/$username"
    | "/projects/$projectId"
    | "/tasks/$taskId"
    | "/projects"
    | "/tasks";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/login"
    | "/signup"
    | "/_auth/$username"
    | "/_auth/projects/$projectId"
    | "/_auth/tasks/$taskId"
    | "/_auth/projects/"
    | "/_auth/tasks/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/$username": {
      id: "/_auth/$username";
      path: "/$username";
      fullPath: "/$username";
      preLoaderRoute: typeof AuthUsernameRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/tasks/": {
      id: "/_auth/tasks/";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof AuthTasksIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/projects/": {
      id: "/_auth/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof AuthProjectsIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/tasks/$taskId": {
      id: "/_auth/tasks/$taskId";
      path: "/tasks/$taskId";
      fullPath: "/tasks/$taskId";
      preLoaderRoute: typeof AuthTasksTaskIdRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/projects/$projectId": {
      id: "/_auth/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof AuthProjectsProjectIdRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthUsernameRoute: typeof AuthUsernameRoute;
  AuthProjectsProjectIdRoute: typeof AuthProjectsProjectIdRoute;
  AuthTasksTaskIdRoute: typeof AuthTasksTaskIdRoute;
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute;
  AuthTasksIndexRoute: typeof AuthTasksIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthUsernameRoute: AuthUsernameRoute,
  AuthProjectsProjectIdRoute: AuthProjectsProjectIdRoute,
  AuthTasksTaskIdRoute: AuthTasksTaskIdRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
  AuthTasksIndexRoute: AuthTasksIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
